=== MattPiszczek/TUM_ISC_EasternPower/SCEasternPower/src/SC13Project/Milestone1/HotelReservation/HotelDB.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/HotelDB" xmlns:tns="http://www.example.org/HotelDB" elementFormDefault="qualified">

    <element name="hotel" type="tns:HotelInfo"></element>
    
    <complexType name="HotelInfo">
    	<sequence>
    		<element name="rooms" type="tns:RoomList" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="bookings" type="tns:BookingList"
    			maxOccurs="1" minOccurs="1">
    		</element>
    	</sequence>
    </complexType>

    <complexType name="BookingList">
    	<sequence>
    		<element name="booking" type="tns:BookingInfo" maxOccurs="unbounded" minOccurs="0"></element>
    	</sequence>
    </complexType>
    
    <complexType name="RoomList">
    	<sequence>
    		<element name="room" type="tns:RoomInfo"
    			maxOccurs="unbounded" minOccurs="0">
    		</element>
    	</sequence>
    </complexType>

    <complexType name="RoomInfo">
    	<sequence>
    		<element name="type" type="string" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="totalAmount" type="int" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="rate" type="int" maxOccurs="1" minOccurs="1"></element>
    	</sequence>
    </complexType>

    <complexType name="BookingInfo">
    	<sequence>
    		<element name="bookingID" type="string" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="type" type="string" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="amount" type="int" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="stayPeriod" type="tns:stayPeriodType" maxOccurs="1" minOccurs="1"></element>
    	</sequence>
    </complexType>

    <complexType name="stayPeriodType">
    	<sequence>
    		<element name="checkin" type="tns:ReservationDateInfo" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="checkout" type="tns:ReservationDateInfo" maxOccurs="1" minOccurs="1"></element>
    	</sequence>
    </complexType>

    <complexType name="ReservationDateInfo">
    	<sequence>
    		<element name="year" type="int" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="month" type="int" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="date" type="int" maxOccurs="1" minOccurs="1"></element>
    	</sequence>
    </complexType>
</schema>

=== MattPiszczek/TUM_ISC_EasternPower/SCEasternPower/src/SC13Project/datasource/ds_29_4.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<hot:hotel xmlns:hot="http://www.example.org/HotelDB" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/HotelDB ../../src/SC12Project/Milestone1/HotelReservation/HotelDB.xsd">
    <hot:rooms>
        <hot:room>
            <hot:type>standard</hot:type>
            <hot:totalAmount>50</hot:totalAmount>
            <hot:rate>100</hot:rate>
        </hot:room>
        <hot:room>
            <hot:type>deluxe</hot:type>
            <hot:totalAmount>10</hot:totalAmount>
            <hot:rate>350</hot:rate>
        </hot:room>
        <hot:room>
            <hot:type>president</hot:type>
            <hot:totalAmount>1</hot:totalAmount>
            <hot:rate>3000</hot:rate>
        </hot:room>
    </hot:rooms>
    <hot:bookings>
        <hot:booking>
            <hot:bookingID>bookingOne</hot:bookingID>
            <hot:type>standard</hot:type>
            <hot:amount>3</hot:amount>
            <hot:stayPeriod>
                <hot:checkin>
                    <hot:year>2012</hot:year>
                    <hot:month>1</hot:month>
                    <hot:date>1</hot:date>
                </hot:checkin>
                <hot:checkout>
                    <hot:year>2012</hot:year>
                    <hot:month>1</hot:month>
                    <hot:date>2</hot:date>
                </hot:checkout>
            </hot:stayPeriod>
        </hot:booking>
        <hot:booking>
            <hot:bookingID>bookingTwo</hot:bookingID>
            <hot:type>standard</hot:type>
            <hot:amount>3</hot:amount>
            <hot:stayPeriod>
                <hot:checkin>
                    <hot:year>2012</hot:year>
                    <hot:month>1</hot:month>
                    <hot:date>1</hot:date>
                </hot:checkin>
                <hot:checkout>
                    <hot:year>2012</hot:year>
                    <hot:month>1</hot:month>
                    <hot:date>5</hot:date>
                </hot:checkout>
            </hot:stayPeriod>
        </hot:booking>
    </hot:bookings>
</hot:hotel>
